### ISSUE TITLE
Problem with GitHub action

### ISSUE THREAD

**Issue by joan-yanqiong** [alstr/todo-to-issue-action#101] opened 2022-01-20 09:43 UTC
Hi, 

I wanted to try out this action. Though for some reason, there are no issues created when I add a todo. The language I am using is python and I am working in a private repo. 

Is there someone who could help me with this? Let me know what additional information you need.

**Comment by alstr** [comment] 2022-01-20 12:43
Hi, I'll try my best.

Can you post the contents of your `workflow.yml` file?

Are the TODOs added in the commit you are pushing?

**Comment by joan-yanqiong** [comment] 2022-01-20 16:00
This is the workflow.yml
'`    name: "Create TODOs"
    on: ["push"]
    jobs:
      build:
        runs-on: "ubuntu-latest"
        steps:
          - uses: "actions/checkout@master"
          - name: "TODO to Issue"
            uses: "alstr/todo-to-issue-action@v4.5"
            with: 
                TOKEN: ${{ secrets.TODO_ACTION }}
                PROJECTS_SECRET: ${{ secrets.TODO_ACTION }}
            id: "todo"`

To answer your question, yes I added to test a todo in the commit, then pushed it.

**Comment by alstr** [comment] 2022-01-20 18:52
You can remove the `with` variables, the token should be set by default. The projects secret is only needed for linking issues to projects, and you need to create a new token for that. So for now just remove both to eliminate any unneccessary complexities.

If you go into the action log, what does it say? Is the action running at all? If it's a public repo I can have a look.

**Comment by joan-yanqiong** [comment] 2022-01-21 06:32
I removed the with variables. In the action log I can see that the action is running and it gets a green checkmark, but there is no issues generated from the todo that i added. .

**Comment by alstr** [comment] 2022-01-21 08:05
If the repo is private, please could you set up a public test repo and reproduce the problem? I should be able to figure out the cause from there.

**Comment by joan-yanqiong** [comment] 2022-01-21 09:45
@alstr, just created a public repo and tested the action again. Now it does work, so maybe it has to do with the fact that my repo is private? 
https://github.com/joan-yanqiong/test_repo.git

**Comment by joan-yanqiong** [comment] 2022-01-21 09:53
I think I know now what it is. I'm using python in a jupyter notebook file, so I guess that's the problem.

**Comment by alstr** [comment] 2022-01-21 11:13
That sounds like the problem. It could be resolved by adding Jupyter support to `syntax.json`. This may be something that's best done with a forked repo given the many languages supported by Jupyter though.

**Closed by alstr** 2022-01-21 11:13 UTC

**Comment by joan-yanqiong** [comment] 2022-01-21 13:10
The thing is I'm not sure how to do this...

**Comment by alstr** [comment] 2022-01-21 14:12
To enable Python support with Jupyter, just add this to the list (including a comma depending on where you add it):

```
{
    "language": "Jupyter Notebook:",
    "markers": [
      {
        "type": "line",
        "pattern": "#"
      },
      {
        "type": "block",
        "pattern": {
          "start": "'''",
          "end": "'''"
        }
      },
      {
        "type": "block",
        "pattern": {
          "start": "\"\"\"",
          "end": "\"\"\""
        }
      }
    ]
  }
```

**Comment by joan-yanqiong** [comment] 2022-01-22 17:05
So I forked the repo and then added the code you mentioned above. Though, I suppose I need to adapt the workflow file as well then. How should I do this, I tried some things, but I'm not really familiar with github actions.

**Comment by alstr** [comment] 2022-01-24 09:06
There shouldn't be much you need to change, just alter `uses:` to target your forked repo rather than this one.

**Comment by joan-yanqiong** [comment] 2022-01-24 11:32
I did this, but then I get this message in the log: 
Could not check pipeline_P2_TF_learning/run_pipeline.ipynb for TODOs as this language is not yet supported by default.
So I'm not sure if I'm doing something wrong

`    name: "Create TODOs"
    on: ["push"]
    jobs:
      build:
        runs-on: "ubuntu-latest"
        steps:
          - uses: "actions/checkout@master"
          - name: "TODO to Issue"
            uses: "joan-yanqiong/todo-to-issue-action@master"
            id: "todo"`

**Comment by alstr** [comment] 2022-01-24 12:23
Update the URL in main.py to target your `syntax.json`:

https://github.com/joan-yanqiong/todo-to-issue-action/blob/0b86812db77c41df4302e985bf53f6c1c700b8c7/main.py#L320

**Comment by joan-yanqiong** [comment] 2022-01-24 12:40
Just made the changes and now it works! Thank you for your patience and help!

**Comment by alstr** [comment] 2022-01-24 15:54
No problem, glad you got it working.
