### ISSUE TITLE
Duplicates.. 

### ISSUE THREAD

**Issue by fazulk** [alstr/todo-to-issue-action#37] opened 2021-01-15 01:16 UTC
Looks like others have brought this up, but i'm getting several duplicates if a todo exists within multiple branches. For instance, 

I create the TODO in one branch, push to gh, and get the issue. 

Merge same branch into Master- I might get another duplicate  issue, or maybe not, it seems random.

Create another branch off of master, and push to GH, get another duplicate issue. 

Setup is basic, but here it is: 
```
name: TODO
on: ["push"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO to Issue"
        uses: alstr/todo-to-issue-action@v2.4.1
        with:
          REPO: ${{ github.repository }}
          BEFORE: ${{ github.event.before }}
          SHA: ${{ github.sha }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: "// TODO"
          COMMENT_MARKER: "//"
          CLOSE_ISSUES: true
        id: "todo"`

**Comment by alstr** [comment] 2021-01-16 15:48
Hi Jeff,

Thanks for the report.

I've just run a few tests to try and replicate this behaviour:

1. Created a new repo and committed some generic code.
2. Created a `test` branch, modified some code, and pushed to new branch.
3. Still on the `test` branch, I added a TODO comment and pushed. That issue was created by the action.
4. Merged `test` into `main`. No duplicates were created.

I tried again with a `test2` branch and the same behaviour occurred (no duplicates), so I am not entirely sure why you are getting this problem.

When you merge the branches, the TODO _could_ be picked up again because it will be analysing a diff that it has already seen. However, the action does check the TODO content to see if an identical one already exists. That is why no duplicate was created when I merged. The action could be running twice, but not with that `workflow` file and again, if they run subsequently, a duplicate should not be created if it already exists (that is the purpose of the hash in the issue body - make sure you haven't removed that).

Are you able to share any commits or logs? Or create a new repo and test it with some basic code?

Here are some other things to bear in mind:

- Issues won't be created on the first commit to `main` or another branch. This is because there's no diff available. If you do add a TODO in the first commit to a branch, it will be added when you merge the branch.
- If you make any changes to a TODO with an existing issue and push a new commit, a new issue will be created, as the hash will be different.
- You can remove the `REPO`, `BEFORE`, `SHA` and `CLOSE_ISSUES` settings from your `workflow.yml`; it won't solve the problem, but they no longer need to be explicitly defined.

If you can provide some more information I would be happy to do some more testing. 😄

**Comment by tshepang** [comment] 2021-01-16 16:48
I had the thought that rebasing also results in dupe issues created?

**Comment by alstr** [comment] 2021-01-17 17:44
@tshepang Yes, I believe that would occur at present. As the actions are effectively stateless, it can be hard to keep track of this sort of thing to determine what’s a rebase and what’s a new issue. I don’t want to take this thread off topic, but aside from manually disabling the action temporally whilst you push the rebase commit, another option could be to add support for a flag in the commit description that lets the action know it’s a rebase. I’m happy to discuss this and other ideas in a separate issue if there’s enough interest. This doesn’t sound like what’s occurring in @fazulk’s case, so I would still like to get to the bottom of that.

**Comment by fazulk** [comment] 2021-01-17 19:40
Thanks for the reply @alstr . I'll run some tests outside my working branches and give it a shot. In the meantime- could moving the line position of the TODO or changing the file name create duplicates?

**Comment by alstr** [comment] 2021-01-18 08:01
Changing line position (by modifying code before or after the TODO) should not have any impact.

Changing the file name is likely to have the effect that I described above in response to @tshepang in the sense that I think the entire renamed file would show up in the commit diff as an addition. The original TODO may be closed if the old file shows up as a deletion. That said, I have not done much testing around this.

A quick way of potentially diagnosing the problem is to take a look at the duplicate issues: are the contents (and the hash) identical? If not, there’s the problem, but if they are the same, then the diff is being processed twice for some reason. If you get chance to do some more testing let me know how you get on and I’ll investigate further.

**Comment by alstr** [comment] 2021-03-17 18:22
Closing due to inactivity but will reopen should additional information become available.

**Closed by alstr** 2021-03-17 18:22 UTC
