### ISSUE TITLE
Duplicated issues

### ISSUE THREAD

**Issue by kjetilhp** [alstr/todo-to-issue-action#24] opened 2020-10-26 12:54 UTC
I'm getting a lot of duplicated issues created, what are the criteria for checking if an issue exist?

I'm not editing the todos but of course the line numbers will change all the time and also filenames will change.

example
```

what? we have to sign in if user have signed in with vipps before!

devent/apps/devent-services/src/app/app.service.ts

Line 70 in 18e42f0

 // TODO: what? we have to sign in if user have signed in with vipps before! 
```
```

what? we have to sign in if user have signed in with vipps before!

devent/apps/devent-services/src/app/app.service.ts

Line 70 in 98b1716

 // TODO: what? we have to sign in if user have signed in with vipps before! 
```

**Comment by alstr** [comment] 2020-10-26 13:05
Hi, thanks for the report. File names and line numbers shouldn't make a difference.

First it checks the commit diff, to see if the TODO block has been added in that commit. There may be some times where this is a false positive, so it encodes the prospective issue body and checks it against currently open issues in the repo, to check it's not duplicating itself.

https://github.com/alstr/todo-to-issue-action/blob/50ac4cb002099de0a2938ef809f79302d29c821d/main.py#L209

I am not 100% sure on the cause of the issue that you're describing. Is there a hash in the body of each issue? If they are the same it is a duplicate and I don't know why that is. If it's different, there's some underlying difference between the issues that would need looking at closer.

**Comment by kjetilhp** [comment] 2020-10-26 13:14
hashes are different, 
46cb0548730750214383d5658f8941dcb2c8d4a2
6d7dbb1c820610261d43279d35b1e611f2c8f8f1
..
had to disable the workflow now after 4 duplicates of every todo
![image](https://user-images.githubusercontent.com/393416/97176457-44fe1400-1795-11eb-97b6-8d79a75a7b5c.png)
(I closed all of them manually)
let me know if you want more info on each issue

**Comment by alstr** [comment] 2020-10-26 13:35
Can you share your `workflow.yaml` configuration? If these are being created on `push`, can you share the sections of the commit/diff?

**Comment by kjetilhp** [comment] 2020-10-26 13:37
```
name: 'Workflow'
on: ['push']
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@master'
      - name: 'TODO to Issue'
        uses: 'alstr/todo-to-issue-action@v2.0'
        with:
          REPO: ${{ github.repository }}
          BEFORE: ${{ github.event.before }}
          SHA: ${{ github.sha }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: '// TODO'
          COMMENT_MARKER: '//'
        id: 'todo'

```

**Comment by kjetilhp** [comment] 2020-10-26 13:44
I'll enable it again and see if I can get the diff

**Comment by kjetilhp** [comment] 2020-10-26 14:10
For some reason now when enabling the workflow again and creating a new TODO - only that one was created and not the ones that was already closed. 
Btw, will the todos be affected by switching/merging branches? or other pull requests? 
If not I'll keep on testing this and get back to you if the same thing happens again

**Comment by alstr** [comment] 2020-10-26 14:57
If it happens again it would be useful to identify what kind of 'duplication' it is:

* If the issues are being created all at the same time, it suggests the action is running more than once.
* If the issue is being 'duplicated' later on (after the original issue was created in an earlier commit), it suggests that the action thinks this is a new TODO for whatever reason. For this to happen, the TODO would have to be in a newly added code block in a pushed commit, and there would have to be no open TODO that matches it. If you'd created and closed the TODO earlier, that might happen, but the code block would have to appear as an addition in the diff again. As the hashes are different, it seems to suggest that these are different issues, though.

The action is purely designed around the `push` event and compares the SHA of the most recent commit on ref before the push with the SHA of the commit that triggered the workflow explained. See the [`before`](https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#push) and [`GITHUB_SHA`](https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables) values.

**Comment by alstr** [comment] 2020-10-26 17:38
If you can reproduce this please reopen. Thanks.

**Comment by Aniwax** [comment] 2021-06-14 11:34
I encountered the same problem when I merge branches. Some of the existing TODOs get recreated again.

**Comment by alstr** [comment] 2021-06-14 12:12
Please can you share your workflow file and repo/logs if public?

**Comment by Aniwax** [comment] 2021-06-14 12:15
This is the code in my workflow file:

```yml


<!--StartFragment-->name: todo_to_issueon: ["push"]jobs:  build:    runs-on: "ubuntu-latest"    steps:      - uses: "actions/checkout@master"      - name: "TODO to Issue"        uses: "alstr/todo-to-issue-action@v2.4.1"        id: "todo"        with:          TOKEN: ${{ secrets.GITHUB_TOKEN }}<!--EndFragment-->


```

**Comment by Aniwax** [comment] 2021-06-14 12:19
Unfortunately, my repo is not public. But here you can see the screen shot of this running job: many new issues are created from this Merge. But all these issues existed already on the cloud. 
![image](https://user-images.githubusercontent.com/71446830/121891138-64917f00-cd1b-11eb-8a3b-5ea3c9d8c9b1.png)

**Comment by alstr** [comment] 2021-06-14 12:40
Hi, thanks for the information.

Can you provide a step-by-step way to reproduce? When I looked into this previously I did the following and couldn't reproduce the problem:

> 1. Created a new repo and committed some generic code.
> 2. Created a `test` branch, modified some code, and pushed to new branch.
> 3. Still on the `test` branch, I added a TODO comment and pushed. That issue was created by the action.
> 4. Merged `test` into `main`. No duplicates were created.
> 
> I tried again with a `test2` branch and the same behaviour occurred (no duplicates).

You could also try updating to the latest version.

**Comment by Aniwax** [comment] 2021-06-17 12:33
Hi @alstr , I created this repo https://github.com/Aniwax/test_repo_todo_toisse to try to reproduce the problem. 
I did the following step:

1. Commit a REAME on main branch.
2. Put some generic code on main branch and a TODO (1st) in this file. Also include the workflow file. [After this commit, this TODO is recognised],
3. I started a new branch `add_more_functionalities`. Went into the `generic_code.py` file. Added 2 lines of code and a new TODO (2nd). [However, this TODO is not picked up to become issue.]
4. I went back to the main branch, created another file  and a new TODO (3rd).  [This TODO  became an Issue after push.]
5. Rebase the `add_more_functionalities` according to main. Nothing happened on the TODO side.
6. Merged `add_more_functionalities` to `main` through pull request, and only then the 2nd TODO became an Issue, after push. 

You can check this in the repo history.

**Comment by Aniwax** [comment] 2021-06-17 13:07
Wait, I just caught a fresh duplicate Issue: 
![image](https://user-images.githubusercontent.com/71446830/122402233-94d85800-cf7d-11eb-9034-b57fb786fe0a.png)

This is linked with 13fd38f3cab6c2efb779da3956ddbc452b008453 commit, which you can see here: https://github.com/Aniwax/test_repo_todo_toisse/commits/add_more_funcionalities

**Comment by Aniwax** [comment] 2021-06-17 13:09
For the record, I use `Github Desktop` to manage repositories and push commits. I use `VScode` to write code. I also have a `git` extension on Vscode, but I never push or commit from there.

**Comment by alstr** [comment] 2021-06-17 16:41
> * Commit a REAME on main branch.
> 
> * Put some generic code on main branch and a TODO (1st) in this file. Also include the workflow file. [After this commit, this TODO is recognised],
> 
> * I started a new branch `add_more_functionalities`. Went into the `generic_code.py` file. Added 2 lines of code and a new TODO (2nd). [However, this TODO is not picked up to become issue.]
> 
> * I went back to the main branch, created another file  and a new TODO (3rd).  [This TODO  became an Issue after push.]
> 
> * Rebase the `add_more_functionalities` according to main. Nothing happened on the TODO side.
> 
> * Merged `add_more_functionalities` to `main` through pull request, and only then the 2nd TODO became an Issue, after push.

Hi @Aniwax, thanks for the detailed reply. It is very helpful.

The process you describe here is the actual current expected behaviour. The reason that the 2nd commit doesn't get picked up at first is that it is the first commit on that branch. When that commit is pushed, the action does not receive a SHA of a previous commit (because one doesn't exist), so it can't load a diff and doesn't run. Initialising with an empty commit is currently one workaround. It does get created when the branch is finally merged though (as you describe) because there is a previous SHA on the `main` branch. I will look at improving this, it's just a bit tricky at the moment.

Regarding the duplicate issue you've got, the issue is also regarding the SHA the action is using.

When you merge the PR, the values are:
```
BEFORE (previous commit on branch): bcd7fca6f662790c54b48aed38962d4cb77be91d
SHA (this commit): f788a040981dee06d69c2f5b5d27f33c730cf105
```
This is the diff: https://github.com/Aniwax/test_repo_todo_toisse/compare/bcd7fca6f662790c54b48aed38962d4cb77be91d...f788a040981dee06d69c2f5b5d27f33c730cf105

The TODO `# TODO: think about some cool functionalities` shows up as an addition in the diff and doesn't already exist so is added.

When you merge the branch, the values are:
```
BEFORE: 97abaaf1cc3dd09571fed61ca78995b4c1e0ca00
SHA: 13fd38f3cab6c2efb779da3956ddbc452b008453
```
This is the diff: https://github.com/Aniwax/test_repo_todo_toisse/compare/97abaaf1cc3dd09571fed61ca78995b4c1e0ca00...13fd38f3cab6c2efb779da3956ddbc452b008453

Even though the TODO `# TODO: think about some cool functionalities` has already been added, it shows up as an addition in the diff so is added. Now that TODO did already exist, which the action checks, but it does it by comparing the issue content. As the original issue includes a URL in the body containing `bcd7fca` but the new one `13fd38f` the contents are not identical, so it gets created.

The initial options that come to mind are:

- Simplify the check to see if an issue already exists: do it based on the issue content excluding the URL. Probably quickest.
- Change the issue config, e.g. to run on one branch.
- Do a more complex lookup to get the correct values for the diff. Not sure about that yet.

**Comment by alstr** [comment] 2021-06-19 08:34
I've added an enhanced check for duplicate issues in the new release, `v4.0.2`. Hopefully that helps a bit. Long term I would like to improve how the action handles rebasing so it's not having to rely on this. Prevention rather than cure.

**Comment by alstr** [comment] 2021-07-22 09:02
I'm closing this now but have opened a separate issue to look into the underlying cause.

**Closed by alstr** 2021-07-22 09:02 UTC
