### ISSUE TITLE
Issues in README.md don't seem to be getting picked up

### ISSUE THREAD

**Issue by dhoss** [alstr/todo-to-issue-action#108] opened 2022-02-18 22:47 UTC
I'm trying to add a TODO in my README.md but it doesn't seem to be getting picked up:

```
<!-- TODO:
Fix maven shade warning:  
[WARNING] chicxulub-1.0-SNAPSHOT.jar, scala-library-2.13.6.jar, scala-reflect-2.13.4.jar, scalactic_2.13-3.2.9.jar define 1 overlapping resource:  
[WARNING]   - META-INF/MANIFEST.MF  
[WARNING] scala-library-2.13.6.jar, scala-reflect-2.13.4.jar define 2 overlapping resources:  
[WARNING]   - LICENSE  
[WARNING]   - NOTICE  
-->
```

I commit + push but no issues are created in my project.

I've tried both `<!--- TODO:` and `<!-- TODO:`, as the syntax.json file for this action defines the block start as ` "start": "<!---",`

I may be doing something stupid though.

**Comment by alstr** [comment] 2022-02-22 17:05
Hey, thanks for the feedback! After doing a bit of testing, I've found a couple of problems:

1. There's a typo in the syntax for Markdown, it should be `<!--` (thanks for the heads up).
2. The issue is not being created regardless of whether you use `<!--` or `<!---` because the issue title is on the second line. If you change it to `<!-- TODO: Fix maven shade warning:`, it should work.

**Comment by alstr** [comment] 2022-03-14 16:10
Closing but if you have any further comments please reply. :smile:

**Closed by alstr** 2022-03-14 16:10 UTC

**Comment by devin-helio** [comment] 2022-03-29 18:22
Hi, this was on my non-work account but I just wanted to say thanks for getting back to me on this and addressing it quickly.
